# version: '3'

# services:
#   mongo:
#     container_name: mongodb
#     restart: always
#     image: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: 'mongo'
#       MONGO_INITDB_ROOT_PASSWORD: 'UFqsXAYnbdERUdRdcrogTCXJouNGNmaN'

#     ports:
#       - '27017:27017'
#     networks:
#       - local

#   app:
#     depends_on:
#       - mongo
#     container_name: api-devbills
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - ./:/home/app
#     ports:
#       - '3333:3333'
#     networks:
#       - local

# networks:
#   local:
#     name: local
